version: '3'
services:
  mongodb:
    image: 'mongo:latest'
    container_name: 'database-mongodb'
    volumes:
      - './mongodb:/docker-entrypoint-initdb.d/'
    ports:
    - '27017:27017'
      
  mariadb:
    image: 'mariadb:latest'
    container_name: 'database-mariadb'
    environment:
      MYSQL_ROOT_PASSWORD: 'pass.123'
    volumes:
    - './mariadb:/docker-entrypoint-initdb.d/'
    ports:
    - '3306:3306'